### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by elig0n** [strboul/git-substatus#2]
tried on two different directories with git repos:

```
Traceback (most recent call last):
  File "/home/eg/.local/bin/git-substatus", line 8, in <module>
    sys.exit(main())
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/__main__.py", line 11, in main
    GitSubstatusApplication(args).exec()
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/gitsubstatus.py", line 59, in exec
    statuses = status.get_status()
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/status.py", line 149, in get_status
    git_status = tuple(self.__get_statuses())
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/status.py", line 154, in __get_statuses
    status = self.__get_git_status(repo)
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/status.py", line 161, in __get_git_status
    if self.__is_status_clean():
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/status.py", line 181, in __is_status_clean
    btw_brackets = self.status_details[0].split("[")
IndexError: list index out of range
```

```
Traceback (most recent call last):
  File "/home/eg/.local/bin/git-substatus", line 8, in <module>
    sys.exit(main())
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/__main__.py", line 11, in main
    GitSubstatusApplication(args).exec()
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/gitsubstatus.py", line 59, in exec
    statuses = status.get_status()
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/status.py", line 149, in get_status
    git_status = tuple(self.__get_statuses())
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/status.py", line 154, in __get_statuses
    status = self.__get_git_status(repo)
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/status.py", line 164, in __get_git_status
    self.status_changes = StatusChanges.get_status_changes(self.status_details)
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/status.py", line 42, in get_status_changes
    cls.mapped_status_count = cls.__get_mapped_status_count()
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/status.py", line 105, in __get_mapped_status_count
    return dict(status_count_gen())
  File "/home/eg/.local/lib/python3.9/site-packages/git_substatus/status.py", line 100, in status_count_gen
    raise KeyError(f"Unknown status mapping: \"{k}\"")
KeyError: 'Unknown status mapping: "?"'
```
also I couldn't get the package from pip via `pip install git-substatus`

**Comment by strboul** [comment]
Hi @elig0n,

I can't reproduce the first issue on my system. Could you provide an example like in [this file](https://github.com/strboul/git-substatus/blob/7ff71047f38757801d5f374e14e8af9abbe38f9e/tests/gen_test_repos.sh#L28)?

The second issue probably comes from here: https://github.com/strboul/git-substatus/blob/7ff71047f38757801d5f374e14e8af9abbe38f9e/git_substatus/status.py#L54

That's because I haven't created all codes for all the statuses. I can handle it at some point but also PRs are welcomed.

I didn't get any errors from `pip install git-substatus`. I also tried it on a fresh VM. What type of errors did you receive?

**Comment by elig0n** [comment]
> I can't reproduce the first issue on my system. Could you provide an example like in [this file](https://github.com/strboul/git-substatus/blob/7ff71047f38757801d5f374e14e8af9abbe38f9e/tests/gen_test_repos.sh#L28)?

I can't seem to reproduce the problem now, so I will close the issue.

> I didn't get any errors from `pip install git-substatus`. I also tried it on a fresh VM. What type of errors did you receive?

I can't remember what it was but it seems to be working fine now.
