### ISSUE TITLE
KeyError: 'Unknown status mapping: "RM"'

### ISSUE THREAD

**Issue by beucismis** [strboul/git-substatus#3]
I'm trying on the home directory where my projects.

Python version: `3.9.2`
git-substatus version: `0.2.3`

```
[ 12:57 ÖS ] [ adil@debian:~/Projects ]
 $ git-substatus 
Traceback (most recent call last):
  File "/usr/local/bin/git-substatus", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/git_substatus/__main__.py", line 11, in main
    GitSubstatusApplication(args).exec()
  File "/usr/local/lib/python3.9/dist-packages/git_substatus/gitsubstatus.py", line 59, in exec
    statuses = status.get_status()
  File "/usr/local/lib/python3.9/dist-packages/git_substatus/status.py", line 149, in get_status
    git_status = tuple(self.__get_statuses())
  File "/usr/local/lib/python3.9/dist-packages/git_substatus/status.py", line 154, in __get_statuses
    status = self.__get_git_status(repo)
  File "/usr/local/lib/python3.9/dist-packages/git_substatus/status.py", line 164, in __get_git_status
    self.status_changes = StatusChanges.get_status_changes(self.status_details)
  File "/usr/local/lib/python3.9/dist-packages/git_substatus/status.py", line 42, in get_status_changes
    cls.mapped_status_count = cls.__get_mapped_status_count()
  File "/usr/local/lib/python3.9/dist-packages/git_substatus/status.py", line 105, in __get_mapped_status_count
    return dict(status_count_gen())
  File "/usr/local/lib/python3.9/dist-packages/git_substatus/status.py", line 100, in status_count_gen
    raise KeyError(f"Unknown status mapping: \"{k}\"")
KeyError: 'Unknown status mapping: "RM"'
```

**Comment by strboul** [comment]
It's because not all statuses are added. I can surely send a patch to fix it but I'd also be happy to assist you if you would like to send a PR. 

Hint: You can add the `RM` key here https://github.com/strboul/git-substatus/blob/7ff71047f38757801d5f374e14e8af9abbe38f9e/git_substatus/status.py#L86 based on the https://github.com/strboul/git-substatus/blob/7ff71047f38757801d5f374e14e8af9abbe38f9e/git_substatus/status.py#L65
information.

**Comment by beucismis** [comment]
Thanks. PR: #4
